### ISSUE TITLE
Add header section

### ISSUE THREAD

**Issue by fjpalacios** [fjpalacios/website-gatsby#3]
### Child tasks

- [x] Add H1 and H2 section
- [x] Add contact section
- [x] Add phone number in print view
