### ISSUE TITLE
Add dark/light mode selector

### ISSUE THREAD

**Issue by fjpalacios** [fjpalacios/website-gatsby#4]
### Child tasks

- [x] Add dark/light mode selector
- [x] Add dark color palette
- [x] Add light color palette
