### ISSUE TITLE
Add about section

### ISSUE THREAD

**Issue by fjpalacios** [fjpalacios/website-gatsby#6]
### Child tasks

- [x] Add about wrapper
- [x] Add about titles
- [x] Add basic list section
- [x] Add advanced list with list of technologies used
- [x] Add content both in English and Spanish languages
